---
# kill Nautilus task
- name: kill nautilus process
  ansible.builtin.command:
    cmd: pkill --full nautilus

# copy gnome settings file to dest task

# copy mimeapps file task

# set permissions on mimeapps file task

# perform dconf update task

# perform lineinfile mod for logind.conf task
...