---
# kill Nautilus task
# need to figure out how to handle error here when Nautilus is not running and the command returns rc:1
- name: kill nautilus process
  ansible.builtin.command:
    cmd: pkill --full nautilus
    #ignore_errors: True # this throws errors about no longer being supported due to legacy

# copy gnome settings file to dest task
- name: copy gnome settings file
  ansible.builtin.copy:
    src: ./etc/dconf/db/local.d/01-gnome-settings
    dest: /etc/dconf/db/local.d/01-gnome-settings

# copy mimeapps file task

- name: debug ansible user name
  ansible.builtin.debug:
    msg: "{{ ansible_facts.ansible_env.USERNAME }}"
    #var: ansible_facts

# - name: copy mimeapps default application settings file
#   ansible.builtin.copy:
#     src: ./home/username/.config/mimeapps.list
#     dest: /home/username/.config/mimeapps.list

# set permissions on mimeapps file task

# perform dconf update task

# perform lineinfile mod for logind.conf task
...