---
- name: remove unwanted packages
  ansible.builtin.dnf:
    name:
      - "cheese"
      - "gnome-boxes"
      - "gnome-contacts"
      - "gnome-maps"
      - "rhythmbox"
      - "simple-scan"
    state: absent

# - name: remove unwanted packages
#   ansible.builtin.dnf:
#     name: "{{ item }}"
#     state: absent
#   with_items:
#     - "{{ unwanted_packages }}"

- name: update multimedia packages
  ansible.builtin.dnf:
    name: '@multimedia'
    state: latest
    update_cache: True
    install_weak_deps: False
    allowerasing: True

- name: update sound-and-video packages
  ansible.builtin.dnf:
    name: '@sound-and-video'
    state: latest
    install_weak_deps: True

# - name: upgrade all current packages
#   ansible.builtin.dnf:
#     name: "*"
#     state: latest
#     update_cache: True

# - name: install base packages
#   ansible.builtin.dnf:
#     name: "{{ item }}"
#     state: present
#   with_items:
#     - "{{ base_packages }}"
...