---
# tasks file for fedora38-workstation
    # - name: debug ansible distro version
    #   ansible.builtin.debug:
    #     msg: "{{ ansible_distribution_version }}"

    # - name: install distribution RPM GPG keys
    #   ansible.builtin.dnf:
    #     name: distribution-gpg-keys
    #     state: present

    - name: enable GPG keys
      ansible.builtin.rpm_key:
        key: "{{ item.path }}"
        state: present
      with_items:
        - "{{ gpg_keys }}"

    - name: install RPM Fusion free and nonfree repos
      ansible.builtin.dnf:
        name: "{{ item.url }}"
        state: present
      with_items:
        - "{{ repos }}"

    - name: install base packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ base_packages }}"
...