---
- name: create terminator directory structure
  ansible.builtin.file:
    path: /home/{{ user_account }}/.config/terminator/
    state: directory
    owner: "{{ user_account }}"
    group: "{{ user_account }}"

- name: copy terminator settings file
  ansible.builtin.copy:
    src: ./home/username/.config/terminator/config
    dest: /home/{{ user_account }}/.config/terminator/config
    owner: "{{ user_account }}"
    group: "{{ user_account }}"

- name: insert custom PS1 into user .bashrc file
  ansible.builtin.lineinfile:
    path: /home/{{ user_account }}/.bashrc
    line: 'export PS1="\[\e]0;\u@\h: \w\a\]\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "'

- name: create vscode directory structure
  ansible.builtin.file:
    path: /home/{{ user_account }}/.config/Code/User/
    state: directory
    owner: "{{ user_account }}"
    group: "{{ user_account }}"

# VS Code default settings: https://code.visualstudio.com/docs/getstarted/settings#_default-settings  
# VS Code privacy settings: https://code.visualstudio.com/docs/supporting/FAQ
- name: copy vscode settings file
  ansible.builtin.copy:
    src: ./home/username/.config/Code/User/settings.json
    dest: /home/{{ user_account }}/.config/Code/User/settings.json
    owner: "{{ user_account }}"
    group: "{{ user_account }}"
...