---
# The transition to GNOME 45 in Fedora 39 broke theme settings (usually found in Tweaks). More here: https://release.gnome.org/45/developers/  
# Legacy applications and applications that use the latest versions of GTK4 now have different settings in the gnome file


# To kill Nautilus, Ansible does not have a kill module, so had to run this one in a non-idempotent way. Hence we must ignore_errors here
- name: kill nautilus process
  ansible.builtin.command:
    cmd: pkill --full nautilus
  ignore_errors: True

# In 01-gnome-settings file, 'color-scheme' coordinates with the UI Settings --> Appearance --> Style option, which applications using GTK4 will obey.  
# Applications still using GTK3 will obey the gtk-theme setting, which coordinates to Tweaks --> Appearance --> Legacy Applications setting.
- name: copy gnome settings file
  ansible.builtin.copy:
    src: ./etc/dconf/db/local.d/01-gnome-settings
    dest: /etc/dconf/db/local.d/01-gnome-settings

- name: copy mimeapps default application settings file
  ansible.builtin.copy:
    src: ./home/username/.config/mimeapps.list
    dest: /home/{{ user_account }}/.config/mimeapps.list
    owner: "{{ user_account }}"
    group: "{{ user_account }}"

# Reference for logind settings: https://www.freedesktop.org/software/systemd/man/logind.conf.html
- name: create logind.conf.d directory
  ansible.builtin.file:
    path: /etc/systemd/logind.conf.d
    state: directory

- name: copy logind settings override file
  ansible.builtin.copy:
    src: ./etc/systemd/logind.conf.d/00-lidsettings.conf
    dest: /etc/systemd/logind.conf.d/00-lidsettings.conf

# potential future placeholder here for tuned-adm command / pdd.conf but currently bugged (see NEWS.md)
# see commands:
# - tuned-adm profile --help
# - tuned-adm verify

# A dconf update is necessary to load the new dconf settings. Even rebooting the system will not do this
- name: update dconf databases
  ansible.builtin.command:
    cmd: dconf update

# Removed the below feature in Fedora 41 but leaving tasks in place to potentially revisit in the future
# - name: copy Nautilus Template files
#   ansible.builtin.copy:
#     src: ./home/username/Templates/
#     dest: /home/{{ user_account }}/Templates/
#     owner: "{{ user_account }}"
#     group: "{{ user_account }}"

# - name: copy nautilus-python scripts to user profile
#   ansible.builtin.copy:
#     src: ./home/username/.local/share/nautilus-python/extensions/
#     dest: /home/{{ user_account }}/.local/share/nautilus-python/extensions/
#     owner: "{{ user_account }}"
#     group: "{{ user_account }}"
...