---
- name: enhance dnf speeds
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    insertafter: '^\[main\]$'
    line: 'max_parallel_downloads=10'
    state: present
    firstmatch: True

- name: import repo gpg and signing keys
  ansible.builtin.rpm_key:
    key: "{{ item.location }}"
    state: present
  with_items:
    - "{{ repo_keys }}"

- name: install RPM Fusion free and nonfree repos
  ansible.builtin.dnf:
    name: "{{ item.location }}"
    state: present
  with_items:
    - "{{ repos }}"

- name: enable appstream data from RPM Fusion repos
  ansible.builtin.dnf:
    name: '@Core'
    state: latest

- name: copy Microsoft Visual Studio Code repo file
  ansible.builtin.copy:
    src: ./etc/yum.repos.d/vscode.repo
    dest: /etc/yum.repos.d/vscode.repo

- name: enable the google chrome repo
  community.general.ini_file:
    path: /etc/yum.repos.d/google-chrome.repo
    section: google-chrome
    option: enabled
    value: 1
    backup: True

# method must be system, not user, and yes you can still use without sudo doing this
- name: add flathub repo to user space
  community.general.flatpak_remote:
    name: flathub
    state: present
    enabled: True
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
...
